# Generated by Django 3.1.2 on 2020-11-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcall',
            name='max_calls',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
