# Generated by Django 3.1.2 on 2020-11-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_client', '0002_testcall_max_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='class_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
