# Generated by Django 3.1.2 on 2020-11-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_client', '0003_test_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='url',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='test',
            name='class_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
